global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost']
   - job_name: 'ubademy'
         metrics_path: '/metrics'
         scheme: http
         static_configs:
           - targets: ['ubademy-grupo-13-cursos.herokuapp.com']
